name: Sync Schema Update to Website

on:
  push:
    branches:
      - master
      - automate-spec-update-to-website

    paths:
     # Monitor changes in this v3 file
      - schemas/3.0.0-without-$id.json

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spec-json-schema repo
        uses: actions/checkout@v3
        
      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: acethecreator/website
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          path: ./website

      - name: Copy version 3 Schema File
        run: |
          cp schemas/3.0.0-without-\$id.json website/config/3.0.0.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
          path: website
          commit-message: "chore: sync latest spec json schema updates"
          committer: asyncapi-bot <info@asyncapi.io>
          author: asyncapi-bot <info@asyncapi.io>
          title: "chore: sync latest spec-json-schema update"
          body: |
            Automated Pull Request to sync latest schema update from spec-json-schema repository.
            
            Updates to: `config/3.0.0-without-$id.json`
          branch: update-schema-${{ github.sha }}
          labels: |
            automated
            spec-json-schema-sync
          base: master
          delete-branch: true