name: Sync Schema Update to Website

on:
  push:
    branches:
      - master
      - automate-spec-update-to-website
    paths:
      - schemas/3.0.0-without-$id.json # Monitor changes in this v3 file

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spec-json-schema repo
        uses: actions/checkout@v3
        
      - name: Debug Token Presence
        run: |
          if [ -n "${{ secrets.GH_TOKEN }}" ]; then
            echo "Token is present"
          else
            echo "Token is empty"
          fi

      - name: Checkout website repo
        uses: actions/checkout@v3
        with:
          repository: acethecreator/website
          token: ${{ secrets.GH_TOKEN }}
          path: ./website

      - name: Copy Schema File
        run: |
          cp -r schemas/3.0.0-without-\$id.json website/config

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: website
          commit-message: "chore: sync latest schema updates"
          committer: asyncapi-bot <info@asyncapi.io>
          author: asyncapi-bot <info@asyncapi.io>
          title: "chore: sync latest schema update"
          body: |
            Automated PR to sync latest schema update from spec-json-schema repository.
            
            Updates to: `3.0.0-without-$id.json`
            Triggered by commit: ${{ github.sha }}
          branch: update-schema
          labels: |
            automated
            schema-sync
          base: master
          delete-branch: true